config/routes.rb
Rails.application.routes.draw do
  resources :sessions
  resources :moves
  resources :pokeballs
  resources :pokemons
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get    '/login',   to: 'sessions#new', as: 'login'
  post   '/login',   to: 'sessions#create'
  get '/logout',  to: 'sessions#destroy'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/move.rb
class Move < ApplicationRecord
  belongs_to :pokemon 
end

app/models/pokeball.rb
class Pokeball < ApplicationRecord
  belongs_to :pokemon
  belongs_to :user
  validates :pokemon, presence: true
  validates :user, presence: true
end

app/models/pokemon.rb
class Pokemon < ApplicationRecord
  has_many :pokeballs
  has_many :moves
  has_many :users, through: :pokeballs
end

app/models/session.rb
class Session < ApplicationRecord
  validates :username, presence: true
  # validates_inclusion_of :password, in: 7..30
  validates :password, presence: true
  validates :password, confirmation: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :pokeballs
  has_many :pokemons, through: :pokeballs
  validates_uniqueness_of :username
  # validates :password, length: {in: 7..20}
  def password=(password)
    self.password_digest = BCrypt::Password.create(password)
  end

  def authenticate(password)
    BCrypt::Password.new(self.password_digest) == password
  end
  # has_secure_password - why doesn't this work? Does it have to do with my BCrypt?
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :setup_global_errors, :setup_user_stuff
  def setup_global_errors
    @errors = flash[:errors]
  end

  def setup_user_stuff
    if session["user_id"]
      @logged_in_user = User.find(session["user_id"])
    end
  end

  def log_in!(user)
    session[:user_id] = @user.id
  end

  def logged_in?
    !!session[:user_id]
  end
end

app/controllers/moves_controller.rb
class MovesController < ApplicationController
end

app/controllers/pokeballs_controller.rb
class PokeballsController < ApplicationController

  def new
    @pokeball = Pokeball.new
    @pokemons = Pokemon.all
  end

  def create
    @pokeball = Pokeball.new(pokeball_params)
    @pokeball.user_id = session[:user_id]

    if @pokeball.save
      redirect_to @pokeball.pokemon
    else
      render :new
    end
  end

  def destroy
    @pokeball = Pokeball.find(params[:id])
    @user = @pokeball.user
    @pokeball.destroy
    redirect_to user_path(@user)
  end


  private
  def pokeball_params
    params.require(:pokeball).permit(:pokemon_id)
  end
end

app/controllers/pokemons_controller.rb
class PokemonsController < ApplicationController
  before_action :authenticate, only: [:edit, :destroy] #Everytime I edit or delete user, it goes back to sessions/new. Why is that? session[:user_id] is nil.
  def index
    @pokemons = Pokemon.all
  end

  def show
    @pokemon = Pokemon.find(params[:id])
  end

  def new
    @pokemon = Pokemon.new
  end

  def create
    @pokemon = Pokemon.new(pokemon_params)
    redirect_to @pokemon
  end

  def edit

  end

  def update

  end

  def destroy
    @pokemon = Pokemon.find(params[:id])
    @pokemon.pokeballs.destroy(pokeball)
    redirect to pokemons_path
  end

  private

  def pokemon_params
    params.require(:pokemon).permit(:name, :pokemon_type)
  end

  def authenticate
    redirect_to new_session_path unless logged_in?
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.find_by(username: params[:username])
    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_to users_path
    else
      # flash[:errors] = "Invalid name or password."
      redirect_to new_session_path
    end
  end

  def edit
    @user = User.new
  end

  def update
    @user = User.find_by(username: params[:username])
    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user_id
      redirect_to users_path
    else
      flash[:errors] = @user.errors.full_messages
      redirect_to new_session_path
    end
  end

  def destroy
    reset_session
    redirect_to new_session_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate, only: [:destroy, :edit]
  def index
      @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new

    @errors = flash[:errors] || []
    # we're supposed to comment this out because we set up setup_global_errors
  end

  def create

    @user = User.new(user_params)
    if @user.save
      log_in!(@user)
      redirect_to "/users"
    else
      flash[:errors] = @user.errors.full_messages
      redirect_to new_user_path
    end
  end

  def edit
    @user = User.find(params[:id])
    unless @user == @logged_in_user
      redirect_to users_path
    end
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    if @user.save
      redirect_to @user
    else
      render :edit
    end
  end

  def destroy
    User.destroy(params[:id])
    reset_session
    redirect_to users_path
  end

  private
  def user_params
    params.require(:user).permit(:name, :username, :password, :img_url)
  end

  def authenticate

    redirect_to new_session_path unless logged_in?
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/moves_helper.rb
module MovesHelper
end

app/helpers/pokeballs_helper.rb
module PokeballsHelper
end

app/helpers/pokemons_helper.rb
module PokemonsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PokemonAsh</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <div class="bg">

    <header>
      <% if @logged_in_user %>
        <%= @logged_in_user.username %>
        <% else %>
        <%= link_to "New User", new_user_path %>
      <% end %>
      <br>
      <%= link_to "User Index", users_path %><br>
      <%= link_to "Pokemon Index", pokemons_path %><br>
      <% if @logged_in_user %>
        <%= button_to "Logout", logout_path, method: :get %><br>
      <% else %>
        <%= button_to "Login Page", login_path %><br>
      <% end %>
      <% if @errors %>

      <ul>
        <% @errors.each do |error| %>
        <li>
          <%= error %>
        </li>
        <% end %>
      </ul>
      <% end %>

    </header>

    <div class="body-container">
      <%= yield %>
    </div>

  </div>
  </body>
</html>

app/views/pokeballs/new.html.erb
<h1>New Pokeball Form</h1>

<%= form_for @pokeball do |f| %>
<%= f.collection_select :pokemon_id, @pokemons, :id, :name %><br>
<%= f.submit %>
<% end %>

app/views/pokemons/index.html.erb
<h1>These are all the Pokemon:</h1>

<ul>
  <% @pokemons.each do |pokemon| %>
    <ul>
      <%= link_to pokemon.name, pokemon %>
    </ul>
  <% end %>
</ul>

app/views/pokemons/show.html.erb
<h1>This is <%= @pokemon.name %>'s Page </h1>
<img src= <%= @pokemon.imgurl %> >
<h3>These are all of its Trainers:</h3>

<ul>
  <% @pokemon.users.each do |user| %>
    <li><%= link_to user.username, user %></li>
  <% end %>
</ul>

<h3>These are all of <%= @pokemon.name %>'s moves:</h3>

<ul>
  <% @pokemon.moves.each do |move| %>
  <li><%= move.name %> (<%= move.move_type %>)</li>
  <% end %>
</ul>

app/views/users/edit.html.erb
<h1> Update User </h1>
<%= form_for @user do |f| %>
<%= f.label :username %>
<%= f.text_field :username %>
<%= f.label :password %>
<%= f.password_field :password %>
<%= f.label :img_url %>
<%= f.text_field :img_url %>
<%= f.submit %>
<% end %>

app/views/users/index.html.erb
<h1>Here are all the Trainers:</h1>

<!-- <%= link_to "New User", "/users/new" %> -->

<ul>
  <% @users.each do |user| %>
  <li>
    <%= link_to user.username, user %>
  </li>
  <% end %>
</ul>

app/views/users/new.html.erb
<h3>Username cannot be used twice. </h3>

<%= form_for @user do |f| %>
<%= f.label :username %>
<%= f.text_field :username %><br>
<%= f.label :password %>
<%= f.password_field :password %><br>
<%= f.label :img_url %>
<%= f.text_field :img_url %>
<%= f.submit %>
<% end %>

app/views/users/show.html.erb
<h1>This is <%= @user.username %>'s Page </h1>

<h3>These are all of <%= @user.username %>'s Pokemon:</h3>
<% if @user.img_url %>
<img src= <%= @user.img_url %> >
<% else %>
<% end %>
<ul>
  <% @user.pokeballs.each do |pokeball| %>
    <li>
      <%= link_to pokeball.pokemon.name, pokeball.pokemon %>
      <%= form_tag pokeball_path(pokeball), method: "delete" do %>
      <% if @user.id == session[:user_id] %>
        <%= submit_tag "Release Pokemon" %>
      <% end %>
      <% end %>
    </li>
  <% end %>
</ul>
<br>
<%= link_to "Add Pokemon", new_pokeball_path %>
<br>
<% if @user.id == session[:user_id] %>
<%= link_to "Edit User", edit_user_path %>
<% end %>
<br>

<%= form_tag user_path(@user), method: "delete" do %>
  <% if @user.id == session[:user_id] %>
    <%= submit_tag "Delete User" %>
  <% end %>
<% end %>